name: Leslie Lucey Gallery
favicon: null
layout_spectrum: 0.9487813971936703
typography_spectrum: 0.22168966941535473
title: LESLIE LUCEY GALLERY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120d09'
    - '#7e7b76'
    - '#a9a9a9'
    - '#4f2e1b'
    - '#cecfd1'
  brandStrength: 0
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.4454618748277426
purpose: []
