name: Leslie Lucey Gallery
favicon: null
layout_spectrum: 0.9487813971936703
typography_spectrum: 0.22168966941535473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.01747709373012185
  lightness: 0.31513625429943204
  saturation: 0.27507236739620566
  rhythmicContrast: 0.4454618748277426
purpose: []
