name: Leslie Lucey Gallery
favicon: null
layout_spectrum: 0.24148
typography_spectrum: 1
title: LESLIE LUCEY GALLERY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3f434e'
    - '#20232a'
    - '#9b9fab'
    - '#6e7585'
  brandStrength: 0
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.4454618748277426
purpose: []
